# permissions for end users to edit mesons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meson-editor-role
rules:
- apiGroups:
  - network.meson
  resources:
  - mesons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.meson
  resources:
  - mesons/status
  verbs:
  - get
