
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - network.meson
  resources:
  - mesons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.meson
  resources:
  - mesons/finalizers
  verbs:
  - update
- apiGroups:
  - network.meson
  resources:
  - mesons/status
  verbs:
  - get
  - patch
  - update
